# -*- coding: utf-8 -*-
"""ДЗ_Случайные величины.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXhxok2Kc-ESPDX7nJU-JYAdk9175nHv
"""

import numpy as np
trials = 1000000    # Количество попыток
coin_ballance = 1    # Первоначальный баланс
a1, a2, a3, a4, a5, a6, a7, a8, a9= 0, 0, 0, 0, 0, 0, 0, 0, 0
for i in range(trials):
    random_score = np.random.randint(0, 999) # Случайное число
    coin_ballance -= 1
    if random_score == 777:
        coin_ballance += 200
        a1 +=1
    elif random_score == 999:
        coin_ballance += 100
        a2 +=1
    elif random_score == 555:
        coin_ballance += 50
        a3 +=1
    elif random_score == 333:
        coin_ballance += 15
        a4 +=1
    elif random_score == 111:
        coin_ballance += 10
        a5 +=1
    elif (random_score - 77)//100 == (random_score - 77)/100 and random_score != 777:
        coin_ballance += 5
        a6 +=1
    elif ((random_score - 7)//10 == (random_score - 7)/10) and ((random_score - 77)//100 != (random_score - 77)/100) and random_score != 777:
        coin_ballance += 3
        a7 +=1
    elif random_score//100 == random_score/100:
        coin_ballance += 2
        a8 +=1
    elif random_score//10 == random_score/10 and (random_score//100 != random_score/100):
        coin_ballance += 2
        a9 +=1

coin_game = coin_ballance / trials    # сколько теряем/получаем за одну  игру
b = a1 + a2 + a3 + a4 + a5 + a6 + a7 + a8 + a9
c = b / trials

print('Вероятность выиграша = ', c, 'Баланс счета  после  всех попыток = ', coin_ballance, 'рублей ', 'Количество попыток = ', trials, 'Сколько теряем/получаем за одну  игру = ', coin_game, 'рублей ')
print('-777 =', a1, '-999 =', a2, '555 =', a3, '-333 =', a4, '-111 =', a5, '-*77 =', a6, '-**7 =', a7, '-*00 =', a8, '-**0 =', a9)

"""вероятность выпадения 777, 999, 555, 333, 111 = 1/1000 = 0,001,
или 0,001 * 5 = 0,005
вероятность выпадения *77, *00 = 10/1000 = 0,01,
или 0,01 * 2 = 0,02
Вероятность выпадания **7, **0 = 100/1000 = 0,1,
или 0,1 * 2 = 0,2
Итого вероятность положительного исхода = 0,225

Игра не выгодна.
Игрок в среднем за ход теряет примерно 20 копеек с каждого вложенного рубля.
"""