# -*- coding: utf-8 -*-
"""ДЗ_Pandas_Уваров_Д_В.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTSuQ2gt_jiWWANu4G-bDM6p6ZdesL6v
"""

import pandas as pd
data_movies = pd.read_csv('movies.csv')
data_ratings = pd.read_csv('ratings.csv')
ratings_5_max = data_ratings[data_ratings['rating'] == 5].value_counts('movieId').index[0]
data_movies.title[data_movies.movieId == ratings_5_max]

data = pd.read_csv('power.csv')
data.head()

country_stats = data.filter(items = ['country', 'quantity'])
country_stats.head()



data['country'].unique()

data[ data['country'].str.contains('esto', case=False) ]['country'].unique()

data[ data['country'].str.contains('lit', case=False) ]['country'].unique()

data[ data['country'].str.contains('lat', case=False) ]['country'].unique()

filtered_countries = data[ (data['country']=='Estonia') | (data['country']=='Lithuania') | (data['country']=='Latvia')]

filtered_countries.head()

filtered_years = filtered_countries[(filtered_countries['year'] > 2004) & (filtered_countries['year'] < 2011) ]

filtered_years.head()

filtered_category = filtered_years[(filtered_years['quantity'] >0) &
                                   ((filtered_years['category'] == 4) |
                                    (filtered_years['category'] == 12) |
                                    (filtered_years['category'] == 21))]

filtered_category.head()

ratings_grouped = filtered_category.groupby('country')['quantity'].agg([sum])
ratings_grouped

pd.read_html('https://www.finanz.ru/', encoding='utf-8')[0]

page_url = 'https://www.finanz.ru/valyuty/usd-rub'

df = pd.read_html(page_url, attrs = {'class': 'news_table'}, encoding='utf-8')
df[:1]



