# -*- coding: utf-8 -*-
"""ДЗ_Функции_одной_переменной.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bk72RMnvE3-IfDN1ZmFJjG11vznUzUO3

ДЗ

Уровень 0:
Задание 1
Посчитайте значение первой и второй производной функции:
"""

import sympy as sym
import numpy as np

x = sym.Symbol('x')
f = x**5 + 4*sym.sin(2*x) + sym.cos(3*x + 3)
derivative_f = sym.diff(f,x)
derivative_f

fx = sym.lambdify(x, derivative_f)
fx(1)

derivative_f.evalf(subs={x: 1})

derivative_f2 = sym.diff(f,x,2)
derivative_f2

derivative_f2.evalf(subs={x: 1})

"""Уровень 1:
Задание 2
Постройте график первой и второй производной функции:
sin(2*x+1)**5

На отрезке [-5; 5].
"""

import matplotlib.pyplot as plt
from scipy.misc import derivative
import numpy as np


def function(x):
    return np.sin(2*x+1)**5


def deriv(x):
    return derivative(function, x)
def deriv2(x):
    return derivative(deriv, x)


y = np.linspace(-5, 5)


plt.plot(y, function(y), color='purple', label='Function')


plt.plot(y, deriv(y), color='green', label='Derivative')


plt.plot(y, deriv2(y), color='blue', label='Derivative2')


plt.legend(loc='upper left')
plt.grid(True)