# -*- coding: utf-8 -*-
"""Уваров_Д_В_ДЗ_4 "Основы Python".ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YoqdTc5W3JLtNrurHSx8NbdNAKHYrtms

Домашнее задание к лекции «Функции»
"""

documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

def cmd_p(documents): #Задание 1. Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
    num = input('Введите номер документа: ')
    c =0
    for data in documents:
        if data['number'] == num:
            c += 1
            return print('Владелец документа:', data['name'], end = '\n')
    if c == 0:
        return print('Документ не найден в базе')
def cmd_s(directories): #Задание 1. Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
    num = input('Введите номер документа: ')
    c =0
    for key, value in directories.items():
        if num in value:
            c += 1
            return print('Документ хранится на полке:', key)
    if c == 0:
        return print('Документ не найден в базе')
def cmd_l(documents, directories): #Задание 1. Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
    for data in documents:
        for key, value in directories.items():
            if data['number'] in value:
                numkey = key
        print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')
def cmd_ads(directories): #Задание 1. Пункт 4. Пользователь по команде "ads" может добавить новую полку
    num = input('Введите номер полки: ')
    c =0
    d = []
    if num in directories:
        c += 1
    else:
        directories[num] = []
    for key, value in directories.items():
        d.append(key)
    if c!= 0:
        print('Такая полка уже существует. Текущий перечень полок:', ', '.join(d))
    else:
        print('Полка добавлена. Текущий перечень полок:', ', '.join(d))
def cmd_ds(directories): #Задание 1. Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая)
    num = input('Введите номер полки: ')
    d = []
    if num in directories and directories[num] != []:
        c = 0
    elif num in directories and directories[num] == []:
        del directories[num]
        c = 1
    else:
        c = 3
    for key, value in directories.items():
        d.append(key)
    if c == 0:
        print('На полке есть документы, удалите их перед удалением полки. Текущий перечень полок:', ', '.join(d))
    elif c == 1:
        print('Полка удалена. Текущий перечень полок:', ', '.join(d))
    else:
        print('Такой полки не существует. Текущий перечень полок:', ', '.join(d))
def cmd_ad(documents, directories): #Задание 2. Пункт 1. Пользователь по команде "ad" может добавить новый документ в данные
    num_doc = input('Введите номер документа: ')
    doc_type = input('Введите тип документа: ')
    name_ow = input('Введите владельца документа: ')
    num_dir = input('Введите полку для хранения: ')
    if num_dir in directories:
        doc = {'type': [], 'number': [], 'name': []}
        doc['type'] = doc_type
        doc['number'] = num_doc
        doc['name'] = name_ow
        documents.append(doc)
        for key, value in directories.items():
            if key == num_dir:
                value.append(num_doc)
        print('Документ добавлен. Текущий список документов:')
        for data in documents:
            for key, value in directories.items():
                if data['number'] in value:
                    numkey = key
            print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')
    else:
        print('Такой полки не существует. Добавьте полку командой as.')
        print('Текущий список документов:')
        for data in documents:
            for key, value in directories.items():
                if data['number'] in value:
                    numkey = key
            print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')

def cmd_d(documents, directories): #Задание 2. Пункт 2. Пользователь по команде "d" может удалить документ из данных
    num = input('Введите номер документа: ')
    c, i = 0, 0
    for n in range(len(documents)):
        for key, data in documents[n].items():
            if data == num:
                i = n
                c = 1
    if c == 1:
        del  documents[i]
        for value in directories.values():
            for i in range(len(value)):
                if value[i] == num:
                    del value[i]
        print('Документ удален. Текущий список документов:')
        for data in documents:
            for key, value in directories.items():
                if data['number'] in value:
                    numkey = key
            print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')
    else:
        print('Документ не найден в базе.')
        print('Текущий список документов:')
        for data in documents:
            for key, value in directories.items():
                if data['number'] in value:
                    numkey = key
            print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')


def cmd_m(documents, directories): #Задание 2. Пункт 3. Пользователь по команде "m" может переместить документ с полки на полку
    a, b, c = 0, 0, 0
    d = []
    num = input('Введите номер документа: ')

    for value in directories.values():
        if num in value:
            c +=1

    num_dir = input('Введите номер полки: ')
    for key, value in directories.items():
        if num_dir in directories.keys():
            for i in range(len(value)):
                if value[i] == num:
                    del value[i]
                    a += 1

    for key, value in directories.items():
        if key == num_dir:
            value.append(num)
            b += 1


    if b == 0:
        for key, value in directories.items():
            d.append(key)
        print('Такой полки не существует. Текущий перечень полок: ', ', '.join(d))

    else:
        if c == 0:
            print('Документ не найден в базе. ')
        if a != 0 and b != 0:
            print('Документ перемещен.')
            print('Текущий список документов:')
        for data in documents:
            for key, value in directories.items():
                if data['number'] in value:
                    numkey = key
            print('№: ', data['number'], ',',  ' тип: ', data['type'], ',', ' владелец: ', data['name'], ',', ' полка хранения: ', numkey, sep = '')

def main(documents, directories):
    user_cmd = input('Введите команду: ')
    while user_cmd != 'q':
        if user_cmd == 'p':
            cmd_p(documents)
        elif user_cmd == 's':
            cmd_s(directories)
        elif user_cmd == 'l':
            cmd_l(documents, directories)
        elif user_cmd == 'ads':
            cmd_ads(directories)
        elif user_cmd == 'ds':
            cmd_ds(directories)
        elif user_cmd == 'ad':
            cmd_ad(documents, directories)
        elif user_cmd == 'd':
            cmd_d(documents, directories)
        elif user_cmd == 'm':
            cmd_m(documents, directories)
        else:
            print('Введена неизвестная команда. Введите команду из списка: p, s, l, ads, ds, ad, d, m, q')
        user_cmd = input('Введите команду: ')
    print('Работа приложения завершена. До свидания!')
main(documents, directories)