# -*- coding: utf-8 -*-
"""Шифр Цезаря.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178yHgh11dpvnyL5RPBLoz9sscFOTcyYz
"""

def cesars_code_en(text, num):
    for i in text:
        if 65 <= ord(i)<= 90 and (ord(i) + num) < 91:
            print(chr(ord(i) + num), end = '')
        elif 65 <= ord(i)<= 90 and (ord(i) + num) > 91:
            print(chr(ord(i) - 26 + num), end = '')
        elif 97 <= ord(i)<= 122 and (ord(i) + num) < 123:
            print(chr(ord(i) + num), end = '')
        elif 97 <= ord(i)<= 122 and (ord(i) + num) > 122:
            print(chr(ord(i) - 26 + num), end = '')
        else:
            print(chr(ord(i)), end = '')

def cesars_decode_en(text, num):
    for i in text:
        if 64 < ord(i) < (65 + num):
            print(chr(ord(i) + 26 - num), end = '')
        elif (65 + num) <= ord(i) < 97:
            print(chr(ord(i) - num), end = '')
        elif (97 + num) <= ord(i) < 123:
            print(chr(ord(i) - num), end = '')
        elif 96 < ord(i) <= (97 + num):
            print(chr(ord(i) + 26 - num), end = '')
        else:
            print(chr(ord(i)), end = '')

def cesars_code_ru(text, num):
    for i in text:
        if 1040 <= ord(i)<= 1071 and (ord(i) + num) < 1072:
            print(chr(ord(i) + num), end = '')
        elif 1040 <= ord(i)<= 1071 and (ord(i) + num) > 1072:
            print(chr(ord(i) - 32 + num), end = '')
        elif 1072 <= ord(i)<= 1103 and (ord(i) + num) < 1104:
            print(chr(ord(i) + num), end = '')
        elif 1072 <= ord(i)<= 1103 and (ord(i) + num) > 1103:
            print(chr(ord(i) - 32 + num), end = '')
        else:
            print(chr(ord(i)), end = '')

def cesars_decode_ru(text, num):
    for i in text:
        if 1039 < ord(i) < (1040 + num):
            print(chr(ord(i) + 32 - num), end = '')
        elif (1040 + num) <= ord(i) < 1072:
            print(chr(ord(i) - num), end = '')
        elif (1072 + num) <= ord(i) < 1104:
            print(chr(ord(i) - num), end = '')
        elif 1071 < ord(i) <= (1072 + num):
            print(chr(ord(i) + 32 - num), end = '')
        else:
            print(chr(ord(i)), end = '')


s = input()
#n = int(input())
a = s.split(' ')
#print(s, a)
f = 0
d = list()
#print(ord('Y'), ord('C'), ord('J'), chr(92))
#print(ord('A'), ord('Z'), ord('a'), ord('z'))
#for i in range(26):
    #cesars_decode_en(s, i)
#cesars_decode_ru(s, n)
for i in range(len(a)):
    c = 0
    for j in a[i]:
        if 64 < ord(j) < 123:
            c +=1
            f = c
    cesars_code_en(a[i], f)
    print(' ', end = '')
    d.append(f)

"""# Новый раздел"""